// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDpWms03aAPrAjte4LrOT0UTBHOJXNfAc',
    appId: '1:806389475750:web:cc403ce4bd5cf6e1494767',
    messagingSenderId: '806389475750',
    projectId: 'flutter-todo-gorouter',
    authDomain: 'flutter-todo-gorouter.firebaseapp.com',
    storageBucket: 'flutter-todo-gorouter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8l64LByxvosQJ4N1nGgOToALHVD7_MBs',
    appId: '1:806389475750:android:5d5d3cfa8f30b9c3494767',
    messagingSenderId: '806389475750',
    projectId: 'flutter-todo-gorouter',
    storageBucket: 'flutter-todo-gorouter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDakDKCSJLQ5fistsJWHvFCavK7MTNf7c0',
    appId: '1:806389475750:ios:9fc9e0c018f9aedc494767',
    messagingSenderId: '806389475750',
    projectId: 'flutter-todo-gorouter',
    storageBucket: 'flutter-todo-gorouter.appspot.com',
    iosBundleId: 'com.example.flutterTodoRiverpodGorouterFirebase',
  );
}
